var myApp = angular
	.module("IBC", [])
	.controller("myController", function ($scope) {
		var banners = { 
			bannerHistory: "images/bannerHistory.jpg",
			bannerHistoryTitle: "",
			
			bannerReferences: "images/bannerReferences.jpg",
			bannerReferencesTitle: "",
			
			bannerContact: "images/bannerContact.jpg",
			bannerContactTitle: "",
			
			bannerServicesCorporate: "images/bannerServicesCorporate.jpg",
			bannerServicesCorporateTitle: "",
			bannerServicesTax: "images/bannerServicesTax.jpg",
			bannerServicesTaxTitle: "",
			bannerServicesMergers: "images/bannerServicesBusiness.jpg",
			bannerServicesMergersTitle: "",
			bannerServicesRealstate: "images/bannerServicesRealstate.jpg",
			bannerServicesRealstateTitle: "",
			bannerServicesInvestment: "images/bannerServicesInvestment.jpg",
			bannerServicesInvestmentTitle: "",
			bannerServicesFiduciary: "images/bannerServicesFiduciary.jpg",
			bannerServicesFiduciaryTitle: "",
			bannerServicesNetworks: "images/bannerServicesNetworks.jpg",
			bannerServicesNetworksTitle: "",

			bannerHistoryLang: "../images/bannerHistory.jpg",
			bannerReferencesLang: "../images/bannerReferences.jpg",
			bannerContactLang: "../images/bannerContact.jpg",
			bannerServicesCorporateLang: "../images/bannerServicesCorporate.jpg",
			bannerServicesTaxLang: "../images/bannerServicesTax.jpg",
			bannerServicesMergersLang: "../images/bannerServicesBusiness.jpg",
			bannerServicesRealstateLang: "../images/bannerServicesRealstate.jpg",
			bannerServicesInvestmentLang: "../images/bannerServicesInvestment.jpg",
			bannerServicesFiduciaryLang: "../images/bannerServicesFiduciary.jpg",
			bannerServicesNetworksLang: "../images/bannerServicesNetworks.jpg",
			bannerServicesSecuredLang: "../images/bannerServicesSecured.jpg",

			bannerHistoryTitleES: "Perfil de la Firma",
			bannerReferencesTitleES: "Referencias",
			bannerContactTitleES: "Cont&aacute;ctenos",
			bannerServicesCorporateTitleES: "Servicios Corporativos",
			bannerServicesTaxTitleES: "Servicios de Impuestos y Activos",
			bannerServicesMergersTitleES: "Comision De Negocios: Fusiones &amp; Adquisiciones",
			bannerServicesRealstateTitleES: "Bienes Raices y Sservicios Hipotecarios",
			bannerServicesInvestmentTitleES: "Servicios de Inversion",
			bannerServicesFiduciaryTitleES: "Servicios Fiduciarios",
			bannerServicesNetworksTitleES: "Redes",
			bannerServicesSecuredTitleES: "Inversiones Seguras",

			bannerHistoryTitleFR: "",
			bannerReferencesTitleFR: "",
			bannerContactTitleFR: "",
			bannerServicesCorporateTitleFR: "",
			bannerServicesTaxTitleFR: "",
			bannerServicesMergersTitleFR: "",
			bannerServicesRealstateTitleFR: "",
			bannerServicesInvestmentTitleFR: "",
			bannerServicesFiduciaryTitleFR: "",
			bannerServicesNetworksTitleFR: "",
			bannerServicesSecuredTitleFR: "",

			bannerHistoryTitleGE: "",
			bannerReferencesTitleGE: "",
			bannerContactTitleGE: "",
			bannerServicesCorporateTitleGE: "",
			bannerServicesTaxTitleGE: "",
			bannerServicesMergersTitleGE: "",
			bannerServicesRealstateTitleGE: "",
			bannerServicesInvestmentTitleGE: "",
			bannerServicesFiduciaryTitleGE: "",
			bannerServicesNetworksTitleGE: "",
			bannerServicesSecuredTitleGE: "",

			bannerHistoryTitleRU: "",
			bannerReferencesTitleRU: "",
			bannerContactTitleRU: "",
			bannerServicesCorporateTitleRU: "",
			bannerServicesTaxTitleRU: "",
			bannerServicesMergersTitleRU: "",
			bannerServicesRealstateTitleRU: "",
			bannerServicesInvestmentTitleRU: "",
			bannerServicesFiduciaryTitleV: "",
			bannerServicesNetworksTitleRU: "",
			bannerServicesSecuredTitleRU: "",
		};
		$scope.banners = banners;
	}
);